//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checks()
        {
            this.ProductsInCheck = new HashSet<ProductsInCheck>();
        }
    
        public int IDCheck { get; set; }
        public Nullable<decimal> priceCheck { get; set; }
        public Nullable<System.DateTime> dateAndTimeCheck { get; set; }
        public Nullable<int> IDEmployeeCheck { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInCheck> ProductsInCheck { get; set; }
    }
}
