//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Checks = new HashSet<Checks>();
        }
    
        public int IDEmployee { get; set; }
        public string nameEmployee { get; set; }
        public string phoneEmployee { get; set; }
        public string adressEmployee { get; set; }
        public int experienceEmployee { get; set; }
        public Nullable<int> IDStoreEmployee { get; set; }
        public Nullable<int> IDCategoriesEmployee { get; set; }
        public Nullable<int> IDJobTitleEmployee { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
