//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInSupplies
    {
        public int IDPISupplies { get; set; }
        public Nullable<int> IDProductPISupplies { get; set; }
        public Nullable<int> IDSuppliesPISupplies { get; set; }
        public int amountPISupplies { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
