//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInStores
    {
        public int IDPIS { get; set; }
        public Nullable<int> IDProductsPIS { get; set; }
        public Nullable<int> IDStorePIS { get; set; }
        public int AmountPIS { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
