//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplies()
        {
            this.ProductsInSupplies = new HashSet<ProductsInSupplies>();
        }
    
        public int IDSupplie { get; set; }
        public Nullable<int> IDProviderSupplie { get; set; }
        public Nullable<System.DateTime> dateAndTimeSupplie { get; set; }
        public Nullable<decimal> priceSupplie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInSupplies> ProductsInSupplies { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
